name: video_player
description: "YouTube video player"
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ^3.32.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^16.2.5
  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  # Freezed
  freezed_annotation: ^3.1.0

  # YouTube video player
  youtube_player_flutter: ^9.1.3

  # Theme app
  core_theme:
    path: ../../core/theme
  # Localization app
  core_localization:
    path: ../../core/localization
  # Common
  core_common:
    path: ../../core/common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.0
  freezed: ^3.2.3

flutter:
  uses-material-design: true
