name: main
description: Main screen, progress, downloads, news.
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^16.3.0

  # Theme app
  core_theme:
    path: ../../core/theme
  # Localization app
  core_localization:
    path: ../../core/localization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
