name: core_theme
description: Theme for app.
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.1.5
  # Theme gen
  theme_tailor_annotation: ^3.1.1

  # Core
  core_settings:
    path: ../../core/settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Build
  build_runner: ^2.10.1
  # Theme gen
  theme_tailor: ^3.1.1

flutter:
  uses-material-design: true
