name: auth
description: Auth - Login, Register, Forgot Password, Reset Password, Verify Email, Verify Phone, Verify Code.
version: 0.0.1
homepage: https://github.com/KsArt-IT/BibleStudyWay-Flutter

environment:
  sdk: ^3.9.0
  flutter: ^3.32.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^16.2.5
  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  provider: ^6.1.5
  equatable: ^2.0.7

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  # firebase_storage: ^13.0.0
  # cloud_firestore: ^6.0.0

  # Google Sign In
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.0
  google_sign_in_ios: ^6.2.2

  # Core
  # Common
  core_common:
    path: ../../core/common
  # Theme app
  core_theme:
    path: ../../core/theme
  # Shared widgets and screens
  core_shared:
    path: ../../core/shared
  # Localization app
  core_localization:
    path: ../../core/localization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
