name: core_debug
description: Debug services
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^16.2.5

  # Providers
  provider: ^6.1.5

  # Core
  core_config:
    path: ../config
  core_shared:
    path: ../shared
  core_theme:
    path: ../theme
  core_localization:
    path: ../localization

  # Talker - logger
  talker_flutter: ^5.0.2
  talker_dio_logger: ^5.0.2
  talker_bloc_logger: ^5.0.2
  talker_logger: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
