name: core_shared
description: Shared widgets and resources.
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # SVG
  flutter_svg: ^2.2.1

  # Theme
  core_theme:
    path: ../theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Build
  build_runner: ^2.10.0
  # Flutter gen
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
