name: core_settings
description: Settings service
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Storage
  get_storage: ^2.1.1

  # Navigation
  go_router: ^16.3.0

  # Provider
  provider: ^6.1.5

  # Common
  core_common:
    path: ../../core/common
  # Shared widgets and screens
  core_shared:
    path: ../../core/shared
  # Theme app
  core_theme:
    path: ../../core/theme
  # Localization app
  core_localization:
    path: ../../core/localization
  # Auth
  auth:
    path: ../../features/auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
