name: core_common
description: Common data, interfaces and dependencies.
version: 0.0.1

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_auth: ^6.1.1

  # Core
  core_localization:
    path: ../../core/localization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
