name: core_localization
description: Localization app classes and utilities.
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: any

  # State Management
  provider: ^6.1.5

  # Core
  core_settings:
    path: ../../core/settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
